language: smalltalk
sudo: false
os:
  - linux
install:
  - pip install --user benchupload
smalltalk:
  - Pharo-6.1
  - Pharo-7.0
# bob-bench xUnit file analysis
after_success:
  - benchupload --dir=$SMALLTALK_CI_BUILD
after_failure:
  - benchupload --dir=$SMALLTALK_CI_BUILD